name: "check that we don't need to update translations"
on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  check_no_translations_to_update:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - name: Update the translations
        run: ./scripts/update_translation_files
      - name: Check that the files didn't change
        run: git diff --exit-code
