name: "docker nightly"

on:
  push:
    branches:
      - main
  schedule:
   - cron: "30 9 * * *"

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - run: sudo rm -rf /usr/lib/jvm /usr/share/dotnet	/usr/share/swift /usr/local/.ghcup /usr/local/lib/android/sdk
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@e50058a0fcd8d1a7d626c905502d010a468bf238 # v4.4.1

      - name: Login to DockerHub
        uses: step-security/docker-login-action@8c7b695d8738c5699a679ff5254baf0f19f20a94 # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: step-security/docker-build-push-action@b736dc8a921e02a288f956d3dd9111e276a4cfec # v7.4.0
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            certpl/artemis:${{ github.sha }}
            certpl/artemis:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
