name: "tests"
on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: set RUNNING_ON_GITHUB in env.test
        run: echo RUNNING_ON_GITHUB=1 >> env.test
      - name: run tests
        run: ./scripts/test
