name: "tests / e2e"
on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: set RUNNING_ON_GITHUB in env.test
        run: echo RUNNING_ON_GITHUB=1 >> env.test
      - name: run e2e tests
        run: bash ./scripts/test-e2e
